<?php
/* LiangLee Metatags Manager
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Metatags
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File Version.php
 */
$LiangLee_version = '14072012';
$LiangLee_release = '1.1.0';
?>
