<?php
/* LiangLee Metatags Manager
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package LiangLeeFramework
 * @Subpackage LiangLeeMetatags
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File settings.php
 */
/**
* Get Version
**/ 
$plug_ver = LiangLee_version('LiangLeePanel');
$plug_rel = LiangLee_release('LiangLeePanel');

/**
* Resgister Languages
**/
$liang_lee_Metainfo1 = elgg_echo('llee:metas:1');
$liang_lee_Metainfo2 = elgg_echo('llee:metas:2');
$liang_lee_Metainfo3 = elgg_echo('llee:metas:3');
$liang_lee_Metainfo4 = elgg_echo('llee:metas:4');
$liang_lee_Metainfo5 = elgg_echo('llee:metas:5');
$liang_lee_Metainfo6 = elgg_echo('llee:metas:6');
$liang_lee_Metainfo7 = elgg_echo('llee:metas:7');

/**
* Resgister Settings
**/
$liang_lee_SiteMeta_1 = elgg_view("input/text", array(
"name" => "params[LiangLee_keywords]", 
"placeholder" => "Keyword1, keyword2, keyword3",
"value" => $vars['entity']->LiangLee_keywords
));

$liang_lee_SiteMeta_2 = elgg_view("input/text", array(
"name" => "params[LiangLee_description]", 
"placeholder" => "This is a Website for Schools, colleges",
"value" => $vars['entity']->LiangLee_description
));

$liang_lee_SiteMeta_3 = elgg_view("input/text", array(
"name" => "params[LiangLee_author]",
"placeholder" => "Liang Lee", 
"value" => $vars['entity']->LiangLee_author
));

$liang_lee_SiteMeta_4 = elgg_view("input/text", array(
"name" => "params[LiangLee_robots]",
"placeholder" => "index, follow", 
"value" => $vars['entity']->LiangLee_robots
));

$liang_lee_SiteMeta_5 = elgg_view("input/text", array(
"name" => "params[LiangLee_revisit]",
"placeholder" => "2", 
"value" => $vars['entity']->LiangLee_revisit
));

$liang_lee_SiteMeta_6 = elgg_view("input/text", array(
"name" => "params[LiangLee_contentLang]", 
"placeholder" => "cn",
"value" => $vars['entity']->LiangLee_contentLang
));
$settings = <<<__HTML

    <h3>$lleesettings</h3>
    <div>
        <p><i>$liang_lee_Metainfo1</i><br>$liang_lee_SiteMeta_1</p>
		 <p></p>
		<p><i>$liang_lee_Metainfo2</i><br>$liang_lee_SiteMeta_2</p>
		<p></p>
		<p><i>$liang_lee_Metainfo3</i><br>$liang_lee_SiteMeta_3</p>
		<p></p>
		<p><i>$liang_lee_Metainfo4</i><br>$liang_lee_SiteMeta_4</p>
		<p></p>
		<p><i>$liang_lee_Metainfo5</i><br>$liang_lee_SiteMeta_5</p>
		<p></p>
		<p><i>$liang_lee_Metainfo6</i><br>$liang_lee_SiteMeta_6</p>
		<p><i>$liang_lee_Metainfo7</i>
		<p>Release: $plug_rel</p>
		<p>Version: $plug_ver</p>

    </div>
    <hr>
</div>
__HTML;

echo $settings, $title;